AWSTemplateFormatVersion: 2010-09-09
Description: 'Corda + QuickStart VPC, License: Apache 2.0 (Please do not remove) Aug,15,2018 (qs-1odje6ci6)'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration (new VPC)
        Parameters:
          - AvailabilityZones
          - NumberOfAZs
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - VPCCIDR
      - Label:
          default: Corda Configuration
        Parameters:
          - RemoteAccessCIDR
          - CordaAccessCIDR
          - CordaRPCAccessCIDR
          - InstanceType
          - KeyPairName
          - Location
          - CountryCode
          - OneTimeKey
          - TestnetEndpoint
      - Label:
          default: Corda RDS Configuration
        Parameters:
          - DBAutoMinorVersionUpgrade
          - DBBackupRetentionPeriod
          - DBInstanceClass
          - DBMasterUserPassword
          - DBMasterUsername
          - DBMultiAZ
          - DBName
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      Location:
        default: City
      CountryCode:
        default: Country code
      OneTimeKey:
        default: One-time key
      TestnetEndpoint:
        default: Corda Testnet endpoint
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public Subnet 2 CIDR
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Allowed SSH access CIDR
      CordaAccessCIDR:
        default: Allowed Corda ports CIDR
      CordaRPCAccessCIDR:
        default: Allowed Corda RPC access CIDR
      KeyPairName:
        default: SSH key name
      InstanceType:
        default: Corda instance type
      NumberOfAZs:
        default: Number of used Availability Zones
      AvailabilityZones:
        default: Availability Zones
      VPCCIDR:
        default: VPC CIDR
      DBAutoMinorVersionUpgrade:
        default: Automatic upgrade to new Amazon Aurora minor versions
      DBBackupRetentionPeriod:
        default: Database backup retention period
      DBInstanceClass:
        default: Amazon Aurora database instance type
      DBMasterUserPassword:
        default: Database master password
      DBMasterUsername:
        default: Database master username
      DBMultiAZ:
        default: Enable Multi-AZ deployment for database instance
      DBName:
        default: Database name
Parameters:
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. Only two
      Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  CountryCode:
    Description: The ISO 3166-1 alpha-2 code of the country to which the node is
      associated. This does not need to be where the node is physically located.
    Type: String
  Location:
    Description: The city or location to which the node is associated. This does not
      need to be where the node is physically located.
    Type: String
  OneTimeKey:
    Description: The one-time key that you received when you created a new node on
      Corda Testnet (code valid for 1 hour).
    Type: String
  TestnetEndpoint:
    Description: The base URL of Corda Testnet
    Default: https://onboarder.prod.ws.r3.com
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you to
      securely connect to your instance after it launches
    Type: 'AWS::EC2::KeyPair::KeyName'
  InstanceType:
    AllowedValues:
       - t2.nano
       - t2.micro
       - t2.small
       - t2.medium
       - t2.large
       - t3.small
       - t3.medium
       - t3.large
       - m3.large
       - m3.xlarge
       - m3.2xlarge
       - m4.large
       - m4.xlarge
       - m4.2xlarge
       - m4.4xlarge
    Default: t3.large
    Description: Amazon EC2 instance type for the Corda instances
    Type: String
  NumberOfAZs:
    AllowedValues:
      - '2'
    Default: '2'
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the public (DMZ) subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the public (DMZ) subnet 2 located in Availability Zone 2
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access
    Type: String
  CordaAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for Corda access
    Type: String
  CordaRPCAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for Corda RPC access
    Type: String
  DBAutoMinorVersionUpgrade:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Select true/false to setup Auto Minor Version upgrade
    Type: String
  DBBackupRetentionPeriod:
    Default: '7'
    Description: The number of days for which automatic DB snapshots are retained.
    Type: String
  DBInstanceClass:
    AllowedValues:
    - db.r4.large
    - db.r4.xlarge
    - db.r4.2xlarge
    - db.r4.4xlarge
    - db.r4.8xlarge
    - db.r4.16xlarge
    ConstraintDescription: Must select a valid postgress database instance type.
    Default: db.r4.large
    Description: The name of the compute and memory capacity class of the DB instance.
    Type: String
  DBMasterUserPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    ConstraintDescription: Must be at least 8 characters containing letters, numbers
      and symbols.
    Description: The database admin account password. Must be at least 8 characters
      containing letters, numbers and symbols
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'True'
    Type: String
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters.
    Default: cordauser
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DBMultiAZ:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Specifies if the database instance is a multiple Availability Zone
      deployment.
    Type: String
  DBName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters.
    Default: CordaQuickstartDB
    Description: Name of Corda Quick Start database.
    MaxLength: '64'
    MinLength: '5'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-r3-corda/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
Conditions:
  GovCloudCondition: !Equals
    - !Ref AWS::Region
    - us-gov-west-1
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        Fn::Sub:
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - QSS3Region:
            Fn::If:
            - GovCloudCondition
            - s3-us-gov-west-1
            - s3
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref AvailabilityZones
        CreatePrivateSubnets: 'true'
        KeyPairName: !Ref KeyPairName
        NumberOfAZs: !Ref NumberOfAZs
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR
  CordaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        Fn::Sub:
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/corda.template
        - QSS3Region:
            Fn::If:
            - GovCloudCondition
            - s3-us-gov-west-1
            - s3
      Parameters:
        CordaAccessCIDR: !Ref CordaAccessCIDR
        CordaRPCAccessCIDR: !Ref CordaRPCAccessCIDR
        DBAutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
        DBInstanceClass: !Ref DBInstanceClass
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBMasterUsername: !Ref DBMasterUsername
        DBMultiAZ: !Ref DBMultiAZ
        DBName: !Ref DBName
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        CountryCode: !Ref CountryCode
        Location: !Ref Location
        OneTimeKey: !Ref OneTimeKey
        TestnetEndpoint: !Ref TestnetEndpoint
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCCIDR: !GetAtt VPCStack.Outputs.VPCCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
